apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: patch-deployment
spec:
  workspaces:
    - name: source
    #- name: git-basic-auth
  params:
    - name: BUILDER_IMAGE
      type: string
    - name: BRANCH
      type: string
    - name: STAGE
      type: string
    - name: IMAGEURL
      type: string
  steps:
    - name: patch-deployment
      image: $(params.BUILDER_IMAGE)
      command:
        - /bin/bash
      args: ['-c', "imageurl=$(params.IMAGEURL) yq e '.0.value = env(imageurl)' -i $(params.STAGE)/patches/patch-deployment-generated.yaml && echo OPERATION SUCCESSFUL"]      
      workingDir: $(workspaces.source.path)
    - name: test-patch
      image: $(params.BUILDER_IMAGE)
      command:
        - /bin/bash
      args: ['-c', 'kustomize build $(params.STAGE) >> tmp.yaml && rm tmp.yaml && echo OPERATION SUCCESSFUL']
      workingDir: $(workspaces.source.path)
    - name: git-config-mail
      image: $(params.BUILDER_IMAGE)
      command:
        - /bin/bash
      args: ['-c', 'git config --global user.email "pipeline@vop.viada.de" && echo OPERATION SUCCESSFUL']
      workingDir: $(workspaces.source.path)
    - name: git-config-user
      image: $(params.BUILDER_IMAGE)
      command:
        - /bin/bash
      args: ['-c', 'git config --global user.name "tekton" && echo OPERATION SUCCESSFUL']
      workingDir: $(workspaces.source.path)
    - name: add-changes
      image: $(params.BUILDER_IMAGE)
      command:
        - /bin/bash
      args: ['-c', 'git add . && echo OPERATION SUCCESSFUL']
      workingDir: $(workspaces.source.path)
    - name: commit-changes
      image: $(params.BUILDER_IMAGE)
      command:
        - /bin/bash
      args: ['-c', "git commit -m 'update imageurl in deployemnt' && echo OPERATION SUCCESSFUL"]
      workingDir: $(workspaces.source.path)
    #- name: push-changes
    #  image: $(params.BUILDER_IMAGE)
    #  command:
    #    - /bin/bash
    #  args: ['-c', "git push origin HEAD:$(params.BRANCH) && echo OPERATION SUCCESSFUL"]
    #  workingDir: $(workspaces.source.path)
