apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-maven-pipeline-with-push
spec:
  finally:
    - name: patch-prod
      params:
        - name: BUILDER_IMAGE
          value: 'quay.io/schmti/ibm-festival-custom-builder-image:latest'
        - name: BRANCH
          value: main
        - name: STAGE
          value: 40_prod
        - name: IMAGEURL
          value: 'quay.io/<YOURREPO>/ibm-festival-java-app-release:$(params.image_tag)'
      taskRef:
        kind: Task
        name: patch-deployment
      workspaces:
        - name: source
          workspace: gitops-ressources
  params:
    - default: latest
      description: used as ImageTag
      name: image_tag
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/schmti/ibm-festival-app-development.git'
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:da1aedf0b17f2b9dd2a46edc93ff1c0582989414b902a28cd79bad8a035c9ea4
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source-code
    - name: maven-build
      params:
        - name: MAVEN_IMAGE
          value: >-
            gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
        - name: GOALS
          value:
            - package
        - name: PROXY_PROTOCOL
          value: http
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: source-code
        - name: maven-settings
          workspace: source-code
    - name: build-snapshot-image
      params:
        - name: IMAGE
          value: 'quay.io/<YOURREPO>/ibm-festival-java-app-snapshot:$(params.image_tag)'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:99cae35f40c7ec050fed3765b2b27e0b8bbea2aa2da7c16408e2ca13c60ff8ee
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: PUSH_EXTRA_ARGS
          value: >-
            --creds=<QUAY-USER>:<QUAY-PASSWORD>
      runAfter:
        - maven-build
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source-code
    - name: maven-integration-test
      params:
        - name: MAVEN_IMAGE
          value: >-
            gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
        - name: GOALS
          value:
            - integration-test
        - name: PROXY_PROTOCOL
          value: http
      runAfter:
        - patch-test
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: source-code
        - name: maven-settings
          workspace: source-code
    - name: build-realease
      params:
        - name: IMAGE
          value: 'quay.io/<YOURREPO>/ibm-festival-java-app-release:$(params.image_tag)'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:99cae35f40c7ec050fed3765b2b27e0b8bbea2aa2da7c16408e2ca13c60ff8ee
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: PUSH_EXTRA_ARGS
          value: >-
            --creds=<QUAY-USER>:<QUAY-PASSWORD>
      runAfter:
        - maven-integration-test
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source-code
    - name: clone-gitops-repo
      params:
        - name: url
          value: 'https://github.com/schmti/ibm-festival-app-deployment.git'
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:da1aedf0b17f2b9dd2a46edc93ff1c0582989414b902a28cd79bad8a035c9ea4
        - name: userHome
          value: /tekton/home
      runAfter:
        - build-snapshot-image
        - maven-build
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: gitops-ressources
    - name: patch-test
      params:
        - name: BUILDER_IMAGE
          value: 'quay.io/schmti/ibm-festival-custom-builder-image:latest'
        - name: BRANCH
          value: main
        - name: STAGE
          value: 20_test
        - name: IMAGEURL
          value: 'quay.io/<YOURREPO>/ibm-festival-java-app-snapshot:$(params.image_tag)'
      runAfter:
        - clone-gitops-repo
      taskRef:
        kind: Task
        name: patch-deployment
      workspaces:
        - name: source
          workspace: gitops-ressources
    - name: patch-int
      params:
        - name: BUILDER_IMAGE
          value: 'quay.io/schmti/ibm-festival-custom-builder-image:latest'
        - name: BRANCH
          value: main
        - name: STAGE
          value: 30_int
        - name: IMAGEURL
          value: 'quay.io/<YOURREPO>/ibm-festival-java-app-release:$(params.image_tag)'
      runAfter:
        - build-realease
      taskRef:
        kind: Task
        name: patch-deployment
      workspaces:
        - name: source
          workspace: gitops-ressources
  workspaces:
    - name: source-code
    - name: gitops-ressources
